version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://reckon:reckon123@postgres:5432/reckon_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - reckon-network

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=reckon_db
      - POSTGRES_USER=reckon
      - POSTGRES_PASSWORD=reckon123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - reckon-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - reckon-network

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - reckon-network

volumes:
  postgres_data:
  redis_data:

networks:
  reckon-network:
    driver: bridge
